/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Flex;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.io.File;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.nio.ByteBuffer;

/**
 *
 * @author SHARON
 */
public class Editable extends javax.swing.JFrame {
    private static final String userName = "root";
    private static final String password = "sharonsimon";
    private static final String dataConnect = "jdbc:mysql://localhost:3306/stddb";
  
    public static byte[] intTobyte(int num){
    return ByteBuffer.allocate(4).putInt(num).array();
}
    
    Connection sqlConnect = null;
    PreparedStatement prepStat = null;
    ResultSet rsltSet = null;
    ResultSet rsltSetcount = null;
    String fileName = null;
    int number = 0;
    byte[] photo = intTobyte(number);
    /**
     * Creates new form Editable
     */
    public Editable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAdminNoE = new javax.swing.JTextField();
        txtLastNameE = new javax.swing.JTextField();
        txtFatherNameE = new javax.swing.JTextField();
        txtMotherNameE = new javax.swing.JTextField();
        txtAgeE = new javax.swing.JTextField();
        txtCityE = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtFirstNameE = new javax.swing.JTextField();
        pnlPhoto = new javax.swing.JPanel();
        lblPhotoE = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtEmailE = new javax.swing.JTextField();
        cboGenderE = new javax.swing.JComboBox<>();
        btnClose = new javax.swing.JButton();
        txtPhoneE = new javax.swing.JTextField();
        btnEditPhoto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Record", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel2.setFocusable(false);
        jPanel2.setMaximumSize(new java.awt.Dimension(126, 125));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Last Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Father's Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 202, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Age:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 352, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Gender:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 302, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Mother's Name:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 252, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Admission Number:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 42, -1, -1));
        jPanel2.add(txtAdminNoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 42, 160, -1));
        jPanel2.add(txtLastNameE, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 140, 160, -1));
        jPanel2.add(txtFatherNameE, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 202, 160, -1));

        txtMotherNameE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotherNameEActionPerformed(evt);
            }
        });
        jPanel2.add(txtMotherNameE, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 252, 160, -1));
        jPanel2.add(txtAgeE, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 352, 160, -1));
        jPanel2.add(txtCityE, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 402, 160, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("City:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 402, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Phone:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 452, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(102, 102, 102));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(204, 204, 204));
        btnUpdate.setText("Update");
        btnUpdate.setBorderPainted(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("First Name:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 92, -1, -1));
        jPanel2.add(txtFirstNameE, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 92, 160, -1));

        pnlPhoto.setBackground(new java.awt.Color(51, 51, 51));
        pnlPhoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlPhoto.setToolTipText("");

        javax.swing.GroupLayout pnlPhotoLayout = new javax.swing.GroupLayout(pnlPhoto);
        pnlPhoto.setLayout(pnlPhotoLayout);
        pnlPhotoLayout.setHorizontalGroup(
            pnlPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPhotoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblPhotoE, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlPhotoLayout.setVerticalGroup(
            pnlPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPhotoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblPhotoE, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(pnlPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 130, 129));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("E-mail Address:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 502, -1, -1));

        txtEmailE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailEActionPerformed(evt);
            }
        });
        jPanel2.add(txtEmailE, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 500, 160, -1));

        cboGenderE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Male", "Female" }));
        cboGenderE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGenderEActionPerformed(evt);
            }
        });
        jPanel2.add(cboGenderE, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 302, 160, -1));

        btnClose.setBackground(new java.awt.Color(102, 102, 102));
        btnClose.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(204, 204, 204));
        btnClose.setText("Close");
        btnClose.setBorderPainted(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel2.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, -1, -1));

        txtPhoneE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneEActionPerformed(evt);
            }
        });
        jPanel2.add(txtPhoneE, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 452, 160, -1));

        btnEditPhoto.setBackground(new java.awt.Color(102, 102, 102));
        btnEditPhoto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEditPhoto.setForeground(new java.awt.Color(204, 204, 204));
        btnEditPhoto.setText("Edit Photo");
        btnEditPhoto.setBorderPainted(false);
        btnEditPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPhotoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMotherNameEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotherNameEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotherNameEActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       try
        {   
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            sqlConnect = DriverManager.getConnection(dataConnect,userName,password);
            prepStat = sqlConnect.prepareStatement("update studentdb set surname=?, firstName=?, gender=?, fatherName=?, motherName=?, City=?, Age=?, phone=?, eMail=?, photo=? where adminNo =?" );
            
            
            prepStat.setString(1,txtLastNameE.getText());
            prepStat.setString(2,txtFirstNameE.getText());
            prepStat.setString(3, (String)cboGenderE.getSelectedItem());
            prepStat.setString(4, txtFatherNameE.getText());
            prepStat.setString(5, txtMotherNameE.getText());
            prepStat.setString(6, txtCityE.getText());
            prepStat.setString(7, txtAgeE.getText());
            prepStat.setString(8, txtPhoneE.getText());
            prepStat.setString(9, txtEmailE.getText());
            prepStat.setBytes(10, photo);
            prepStat.setString(11, txtAdminNoE.getText());
            prepStat.executeUpdate();
            btnUpdate.setEnabled(false);
            Flex fx = new Flex();
            fx.updateSystem();
            JOptionPane.showMessageDialog(this,"Student record updated!");
            this.hide();
            fx.hide();
            fx.setVisible(true);
           
            
        }
        
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Flex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtEmailEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailEActionPerformed

    private void cboGenderEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGenderEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboGenderEActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.hide();
        Flex fx = new Flex();
        fx.setVisible(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtPhoneEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneEActionPerformed

    private void btnEditPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPhotoActionPerformed
        
        JFileChooser choose = new JFileChooser();
        choose.showOpenDialog(null);
        File file = choose.getSelectedFile();
        fileName = file.getAbsolutePath();
        lblPhotoE.setIcon(new ImageIcon(file.toString()));

        try{

            File image = new File(fileName);
            FileInputStream fileStream = new FileInputStream(image);
            ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
            byte[] b = new byte[1024];
            for(int readNum; (readNum = fileStream.read(b))!=-1;){
                byteStream.write(b,0,readNum);
            }
            photo = byteStream.toByteArray();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnEditPhotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEditPhoto;
    private javax.swing.JButton btnUpdate;
    public static javax.swing.JComboBox<String> cboGenderE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lblPhotoE;
    private javax.swing.JPanel pnlPhoto;
    public static javax.swing.JTextField txtAdminNoE;
    public static javax.swing.JTextField txtAgeE;
    public static javax.swing.JTextField txtCityE;
    public static javax.swing.JTextField txtEmailE;
    public static javax.swing.JTextField txtFatherNameE;
    public static javax.swing.JTextField txtFirstNameE;
    public static javax.swing.JTextField txtLastNameE;
    public static javax.swing.JTextField txtMotherNameE;
    public static javax.swing.JTextField txtPhoneE;
    // End of variables declaration//GEN-END:variables
}
